version: "3.8"

networks:
  default:
    external: true
    name: npm

services:
  chatgpt-telegram-bot:
    container_name: chatgpt-telegram-bot
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
